name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Build Docker Image
      run: docker build -t vishnu-cicd-app .

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Tag and Push Docker Image to DockerHub
      run: |
        docker tag vishnu-cicd-app ${{ secrets.DOCKER_USERNAME }}/vishnu-cicd-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/vishnu-cicd-app:latest
